/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AboutRouteImport } from './routes/about'
import { Route as ContactRouteImport } from './routes/contact'
import { Route as ServicesRouteImport } from './routes/services'
import { Route as VijayawadaHairBeautyClinicRouteImport } from './routes/vijayawada-hair-beauty-clinic'
import { Route as BranchesCityRouteImport } from './routes/branches.$city'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AboutRoute = AboutRouteImport.update({
  id: '/about',
  path: '/about',
  getParentRoute: () => rootRouteImport,
} as any)
const ContactRoute = ContactRouteImport.update({
  id: '/contact',
  path: '/contact',
  getParentRoute: () => rootRouteImport,
} as any)
const ServicesRoute = ServicesRouteImport.update({
  id: '/services',
  path: '/services',
  getParentRoute: () => rootRouteImport,
} as any)
const VijayawadaHairBeautyClinicRoute =
  VijayawadaHairBeautyClinicRouteImport.update({
    id: '/vijayawada-hair-beauty-clinic',
    path: '/vijayawada-hair-beauty-clinic',
    getParentRoute: () => rootRouteImport,
  } as any)
const BranchesCityRoute = BranchesCityRouteImport.update({
  id: '/branches/$city',
  path: '/branches/$city',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/contact': typeof ContactRoute
  '/services': typeof ServicesRoute
  '/vijayawada-hair-beauty-clinic': typeof VijayawadaHairBeautyClinicRoute
  '/branches/$city': typeof BranchesCityRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/contact': typeof ContactRoute
  '/services': typeof ServicesRoute
  '/vijayawada-hair-beauty-clinic': typeof VijayawadaHairBeautyClinicRoute
  '/branches/$city': typeof BranchesCityRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/contact': typeof ContactRoute
  '/services': typeof ServicesRoute
  '/vijayawada-hair-beauty-clinic': typeof VijayawadaHairBeautyClinicRoute
  '/branches/$city': typeof BranchesCityRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/about'
    | '/contact'
    | '/services'
    | '/vijayawada-hair-beauty-clinic'
    | '/branches/$city'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/about'
    | '/contact'
    | '/services'
    | '/vijayawada-hair-beauty-clinic'
    | '/branches/$city'
  id:
    | '__root__'
    | '/'
    | '/about'
    | '/contact'
    | '/services'
    | '/vijayawada-hair-beauty-clinic'
    | '/branches/$city'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AboutRoute: typeof AboutRoute
  ContactRoute: typeof ContactRoute
  ServicesRoute: typeof ServicesRoute
  VijayawadaHairBeautyClinicRoute: typeof VijayawadaHairBeautyClinicRoute
  BranchesCityRoute: typeof BranchesCityRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/about': {
      id: '/about'
      path: '/about'
      fullPath: '/about'
      preLoaderRoute: typeof AboutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/contact': {
      id: '/contact'
      path: '/contact'
      fullPath: '/contact'
      preLoaderRoute: typeof ContactRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/services': {
      id: '/services'
      path: '/services'
      fullPath: '/services'
      preLoaderRoute: typeof ServicesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/vijayawada-hair-beauty-clinic': {
      id: '/vijayawada-hair-beauty-clinic'
      path: '/vijayawada-hair-beauty-clinic'
      fullPath: '/vijayawada-hair-beauty-clinic'
      preLoaderRoute: typeof VijayawadaHairBeautyClinicRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/branches/$city': {
      id: '/branches/$city'
      path: '/branches/$city'
      fullPath: '/branches/$city'
      preLoaderRoute: typeof BranchesCityRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AboutRoute: AboutRoute,
  ContactRoute: ContactRoute,
  ServicesRoute: ServicesRoute,
  VijayawadaHairBeautyClinicRoute: VijayawadaHairBeautyClinicRoute,
  BranchesCityRoute: BranchesCityRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
