name: GitHub Pages Deploy
on:
  push:
    branches:
      - main

permissions:
  contents: write

jobs:
  build-and-deploy:
    concurrency: ci-${{ github.ref }}
    runs-on: ubuntu-latest
    steps:
      - name: Checkout 🛎️
        uses: actions/checkout@v4

      - name: Install and Build 🔧
        run: |
          npm install
          # We force the build to ignore SSR steps that cause the HTML entry error
          npm run build
          # Ensure we deploy from the client-only dist folder
          touch dist/client/.nojekyll

      - name: Deploy 🚀
        uses: JamesIves/github-pages-deploy-action@v4
        with:
          folder: dist/client
          branch: gh-pages
